export const ACTION_TYPES = {
  VEHICLE_UPDATED: "VEHICLE_UPDATED",
  VEHICLE_CREATED: "VEHICLE_CREATED",
  VEHICLE_DELETED: "VEHICLE_DELETED",
  GET_VEHICLE: "GET_VEHICLE",
  GET_ALL_VEHICLES: "GET_ALL_VEHICLES",
} as const;

export type EventTypes = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES];
