import type { Metadata } from "next";
import { Overpass_Mono, Roboto_Flex } from "next/font/google";
import "./globals.css";
import Providers from "@/components/app/providers";

const robotoFlex = Roboto_Flex({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const overpassMono = Overpass_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${robotoFlex.variable} ${overpassMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
