name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI tab
jobs:
  # ----------------------------------------
  # JOB 1: Build images and push to ECR
  # ----------------------------------------
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push nestjs (NestJS)
        run: |
          REGISTRY=${{ secrets.ECR_REGISTRY }}
          TAG=${{ github.sha }}

          docker build \
            -t $REGISTRY/uncle/nestjs:$TAG \
            -t $REGISTRY/uncle/nestjs:latest \
            ./users-service

          docker push $REGISTRY/uncle/nestjs:$TAG
          docker push $REGISTRY/uncle/nestjs:latest

      - name: Build and push express (Express)
        run: |
          REGISTRY=${{ secrets.ECR_REGISTRY }}
          TAG=${{ github.sha }}

          docker build \
            -t $REGISTRY/uncle/express:$TAG \
            -t $REGISTRY/uncle/express:latest \
            ./vehicles-service

          docker push $REGISTRY/uncle/express:$TAG
          docker push $REGISTRY/uncle/express:latest

      - name: Build and push nextjs (Next.js)
        run: |
          REGISTRY=${{ secrets.ECR_REGISTRY }}
          TAG=${{ github.sha }}

          docker build \
            --build-arg NEXT_AUTH_COOKIE_NAME=${{secrets.NEXT_AUTH_COOKIE_NAME}} \
            --build-arg NEXT_AUTH_VERIFY_PATH=${{secrets.NEXT_AUTH_VERIFY_PATH}} \
            --build-arg NEXT_SERVER_USER_SERVICE_API_URL=${{secrets.NEXT_PUBLIC_USER_SERVICE_API_URL}} \
            --build-arg NEXT_PUBLIC_USER_SERVICE_API_URL="${{ secrets.NEXT_PUBLIC_USER_SERVICE_API_URL }}" \
            --build-arg NEXT_PUBLIC_VEHICLE_SERVICE_API_URL="${{ secrets.NEXT_PUBLIC_VEHICLE_SERVICE_API_URL }}" \
            -t $REGISTRY/uncle/nextjs:$TAG \
            -t $REGISTRY/uncle/nextjs:latest \
            ./front
          
          docker push $REGISTRY/uncle/nextjs:$TAG
          docker push $REGISTRY/uncle/nextjs:latest

  # ----------------------------------------
  # JOB 2: Deploy to EC2
  # ----------------------------------------
  deploy:
    needs: build-and-push    # only runs if Job 1 succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get GitHub Runner Public IP
        id: ip
        run: echo "ipv4=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Authorize Runner IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Copy docker-compose.prod.yml to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ec2-user/app/"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Login to ECR from EC2
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
              | docker login --username AWS \
                --password-stdin ${{ secrets.ECR_REGISTRY }}

            cd /home/ec2-user/app

            # Pull new images from ECR
            docker-compose -f docker-compose.prod.yml --env-file .env pull

            # Restart all containers with new images
            docker-compose -f docker-compose.prod.yml --env-file .env up -d

            # Clean up old unused images to save disk space
            docker image prune -f

            echo "✅ Deploy complete"

      - name: Revoke Runner IP from Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32